spring:
  application:
    name: spring-boot-aws-parameter-store
  cloud:
    aws:
      endpoint: http://localhost:4566
      region.static: ap-south-1
      credentials:
        access-key: noop
        secret-key: noop

  config:
    import: aws-parameterstore:/config/spring/
  app:
    httpUrl: ${httpUrl}
