spring:
  application:
    name: spring-boot-aws-sqs
  cloud:
    aws:
      endpoint: http://localhost:4566
      region.static: ap-south-1
      credentials:
        access-key: noop
        secret-key: noop

